### ISSUE TITLE
Include the :active state for the hover effect

### ISSUE THREAD

**Issue by mrmcpowned** [ShellHacksFIU/ShellHacks-2018-Landing#25]
@Jehfkemsy 

https://github.com/ShellHacksFIU/ShellHacks-2018-Landing/blob/6c4fd732e27f3673d6c349b630fdfa59d31e9a93/styles/form.css#L84

All you should have to add is `,input:active` so it does the same thing while someone is writing in the response too

**Comment by Jehfkemsy** [comment]
done, thanks!
